### PR TITLE
allow start method to accept blocks which it can execute and animate …

### PR DESCRIPTION
**Pull request by Thermatix**
…the spinner automatically untill the provided block has finished executing.

### CODE REVIEW

**Comment by piotrmurach** [comment]
Hi Martin,

Thanks for using the lib and contributing! 

I like your idea of automatically stoping when block finishes. However, I have few questions about the proposed solution. I would imagine that accepting a block is akin to:
```ruby
spinner.start
block.call
spinner.stop('message')
```
Therefore if the start where to accept the block I would probably leave the logic as is and add:
```ruby
def start
  ...
  @thread = .... spinning logic
  if block_given?
    yield (this can be put into another thread)
    stop
  end
end
```
The spinning operation was purposefully put inside a thread to make it nonblocking. In your case auto spinning is a synchronous operation. What do you think?

**Comment by Thermatix** [comment]
The reason it's put into a thread is to make it non-blocking but that's only so you can manually control it, without blocking the process you want it to spin for. When you have a block and it automatically starts and stops when that block finishes , it makes needing to put it into a separate thread kinda pointless as you don't have a separate process you want to spin for as you provided a block for it to spin for instead. 

The idea is, automatic spinning for a given block OR manual spinning without a block. 

It's still your lib so if you still want it into separate thread then I don't mind changing it to that way, whatever you decide i'm a-ok with it.

**Comment by piotrmurach** [comment]
> The reason it's put into a thread is to make it non-blocking but that's only so you can manually control it, without blocking the process you want it to spin for. When you have a block and it automatically starts and stops when that block finishes , it makes needing to put it into a separate thread kinda pointless as you don't have a separate process you want to spin for as you provided a block for it to spin for instead. 

It's important to consider semantics here, for example, `File.new` can be used with block or without. The only difference is that the block creates a scope and automatically closes the stream. In similar manner I would imagine the `start` to work. The animation is async regardless whether the block is called or not. When block is passed then the block is run synchronous within the main thread of the `TTY::Spinner` instance. I suppose I'm trying to have consistent behaviour here. This is a discussion point rather than criticisms of your solution. It may well be the way we gonna implement this. I just quickly need to assess it before I get down to merging the solution/reworking the idea.

> The idea is, automatic spinning for a given block OR manual spinning without a block.

Not sure I follow this, the `start` as is allows for automatic/infinite spinning unless instructed to `stop`. There is nothing manual about it as far as I can see. The `spin` method was intended for 'manual' control.

Have you created a simple example to see how your code behaves in both scenarios? Tests are no substitute to actually running the spinner. There is already auto_spin example in examples folder to try.

The checklist idea is something i have considered before but I'm not sure whether it fits into the scope of this library or should be made into a separate dependency. We can discuss this in a separate issue/thread once we sort this out.

**Comment by Thermatix** [comment]
I think I miss-understood, I thought that after you use start, you have to use the `spin` method to animate the spinner but from what you've said it spins automatically. 
So, I changed it so now it starts up a seperate threads for both the spin animation and the given block, and then spin untill the block is finished and then stop the animation.

**Comment by piotrmurach** [comment]
Hi Martin,
Thank you for suggesting and working on this feature. I have released `v0.3.0` that adds new [run call](https://github.com/piotrmurach/tty-spinner#24-run). I have also added `update` call to allow you execute few tasks in succession.

**Comment by Thermatix** [comment]
Awesome sauce, glad could help contribute, I like this contribute thing, I think I might try it somewhere else.

**Comment by piotrmurach** [comment]
Wish you many contributions and all the success on the open source front!

**Pull request merged**
