### PR TITLE
Add demo gif

### PR DESCRIPTION
**Pull request by ReadmeCritic**
:smile:

### CODE REVIEW

**Comment by piotrmurach** [comment]
Sorry forgotten to respond to this issue. Would you have time to record this demo again?

**Comment by ReadmeCritic** [comment]
Sure.. uh would you like me to do something differently??

**Comment by piotrmurach** [comment]
Would it be possible to zoom in to show just the terminal without the surrounding desktop backdrop? As for animation itself, since new version we have `success` method that shows check mark once spinning is done, this could be paired with some more show-off formatter(take your pick and see what is most exciting)? I hope I'm not pushing you too much :smile:

**Comment by ReadmeCritic** [comment]
will try 😄

**Pull request closed without merging**
